config/routes.rb
Rails.application.routes.draw do
  #get 'transactions/create', to: "transactions#create"
  #get 'transactions/update', to: "transactions#update"
  resources :sales
  resources :inventory_items
  resources :employees
  resources :shops
  resources :product_statuses
  resources :products
  resources :product_types
  # servidores:
  # rails server
  # ruby .\bin\webpack-dev-server
  devise_for :users

  post "payment_details/create", to: "payment_details#create"

  ##Revenue
  get "revenue/", to: "revenue#index"

  ##Home
  get 'home/index', to: "home#index"
  root to: "home#index"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end
## TODO: Crear Modelo para dar permisos y su respectivo controlador y vistas.

app/models/ejemplo.rb
class Ejemplo < ApplicationRecord
end

app/models/employee.rb
class Employee < ApplicationRecord
  has_many :users
  belongs_to :shop
  has_many :inventory_items
  has_many :sales
  has_many :sale_sessions
end

app/models/inventory_item.rb
class InventoryItem < ApplicationRecord
  belongs_to :shop
  belongs_to :product
  belongs_to :product_status
  belongs_to :employee
  has_many :transactions
  has_many :sales, through: :transactions
end

app/models/payment_detail.rb
class PaymentDetail < ApplicationRecord
  belongs_to :sale
end

app/models/player.rb
class Player < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :product_type
  belongs_to :product_subtype
  has_many :inventory_items
end

app/models/product_status.rb
class ProductStatus < ApplicationRecord
  has_many :inventory_items
  scope :as_option, ->{ where("id < 3") }#where({ product_status_id: [1, 2]})
  scope :managable_statuses, ->{ where(managable: 1) }
  scope :unmanagable_statuses, ->{ where(managable: 0) }
end

app/models/product_subtype.rb
class ProductSubtype < ApplicationRecord
  belongs_to :product_type
end

app/models/product_type.rb
class ProductType < ApplicationRecord
  has_many :products
  has_many :product_subtypes
end

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :shop
  belongs_to :employee
  has_many :sale_sessions
  has_many :payment_details
  has_many :transactions
  has_many :inventory_items, through: :transactions

  def create_sale_session
    SaleSession.find_or_create_by(sale: self, employee_id: self.employee_id)
  end

  def  destroy_sale_session
    #SaleSession.where(employee_id: current_user.employee_id).destroy_all
  end

  def test_dev_environ
    puts "################\n  Funciona!  \n################"
  end

  # def sell_inventory_items
  #   inventory_items = self.inventory_items
  #   inventory_items.each do |item|
  #     unless item.update(product_status_id: 4) then
  #       puts "\n\n#{item.errors}\n\n"
  #     end
  #   end
  # end

end

app/models/sale_session.rb
class SaleSession < ApplicationRecord
  belongs_to :employee
  belongs_to :sale
end

app/models/shop.rb
class Shop < ApplicationRecord
  has_many :employees
  has_many :inventory_items
  has_many :sales

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/test_api.rb
class TestApi < ApplicationRecord
    validates :fakeId, presence: true
    validates :title, presence: true
    validates :body, presence: true
    validates :userId, presence: true
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :sale
  belongs_to :inventory_item
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :employee


end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /shops
  # GET /shops.json
  def index
    @shops = Shop.all
  end

  # GET /shops/1
  # GET /shops/1.json
  def show
  end

  # GET /shops/new
  def new
    @shop = Shop.new
  end

  # GET /shops/1/edit
  def edit
  end

  # POST /shops
  # POST /shops.json
  def create
    @shop = Shop.new(shop_params)
    @shop.sku = assign_sku @shop

    respond_to do |format|
      if @shop.save
        format.html { redirect_to @shop, notice: 'Shop was successfully created.' }
        format.json { render :show, status: :created, location: @shop }
      else
        format.html { render :new }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shops/1
  # PATCH/PUT /shops/1.json
  def update
    respond_to do |format|
      if @shop.update(shop_params)
        format.html { redirect_to @shop, notice: 'Shop was successfully updated.' }
        format.json { render :show, status: :ok, location: @shop }
      else
        format.html { render :edit }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shops/1
  # DELETE /shops/1.json
  def destroy
    @shop.destroy
    respond_to do |format|
      format.html { redirect_to shops_url, notice: 'Shop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end



  private

#Invernaderos (id, nombre, direccion, telefono, codigo)
#Ejemplo (id, sku, invernadero_id)

  def assign_sku asdfasf
      if Ejemplo.any? then
        number = Ejemplo.last.id
        #case number
        return sku = asdfasf.invernadero.codigo + number.to_s
      else
        return sku = asdfasf.invernadero.codigo + 0001.to_s
      end
  end
    # Use callbacks to share common setup or constraints between actions.
    def set_shop
      @shop = Shop.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def shop_params
      params.require(:shop).permit(:name, :pseudonym, :address, :city)
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/revenue_helper.rb
module RevenueHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/shops/_form.html.erb
<%= form_with(model: shop, local: true) do |form| %>
  <% if shop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(shop.errors.count, "error") %> prohibited this shop from being saved:</h2>

      <ul>
        <% shop.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, maxlength: 255 %>
  </div>

  <div class="field">
    <%= form.label :pseudonym %>
    <%= form.text_field :pseudonym, required: true %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, required: true %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city, required: true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/shops/edit.html.erb
<h1>Editing Shop</h1>

<%= render 'form', shop: @shop %>

<%= link_to 'Show', @shop %> |
<%= link_to 'Back', shops_path %>

app/views/shops/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Shops</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Pseudonym</th>
      <th>Address</th>
      <th>City</th>
      <th colspan="3">Options</th>
    </tr>
  </thead>

  <tbody>
    <% @shops.each do |shop| %>
      <tr>
        <td><%= shop.name %></td>
        <td><%= shop.pseudonym %></td>
        <td><%= shop.address %></td>
        <td><%= shop.city %></td>
        <td><%= link_to 'Show', shop %></td>
        <td><%= link_to 'Edit', edit_shop_path(shop) %></td>
        <td><%= link_to 'Destroy', shop, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shop', new_shop_path %>

app/views/shops/new.html.erb
<h1>New Shop</h1>

<%= render 'form', shop: @shop %>

<%= link_to 'Back', shops_path %>

app/views/shops/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @shop.name %>
</p>

<p>
  <strong>Pseudonym:</strong>
  <%= @shop.pseudonym %>
</p>

<p>
  <strong>Address:</strong>
  <%= @shop.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @shop.city %>
</p>

<%= link_to 'Edit', edit_shop_path(@shop) %> |
<%= link_to 'Back', shops_path %>