config/routes.rb
Rails.application.routes.draw do
  #get 'transactions/create', to: "transactions#create"
  #get 'transactions/update', to: "transactions#update"
  resources :sales
  resources :inventory_items
  resources :employees
  resources :shops
  resources :product_statuses
  resources :products
  resources :product_types
  # servidores:
  # rails server
  # ruby .\bin\webpack-dev-server
  devise_for :users

  post "payment_details/create", to: "payment_details#create"

  ##Revenue
  get "revenue/", to: "revenue#index"

  ##Home
  get 'home/index', to: "home#index"
  root to: "home#index"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end
## TODO: Crear Modelo para dar permisos y su respectivo controlador y vistas.

app/models/ejemplo.rb
class Ejemplo < ApplicationRecord
end

app/models/employee.rb
class Employee < ApplicationRecord
  has_many :users
  belongs_to :shop
  has_many :inventory_items
  has_many :sales
  has_many :sale_sessions
end

app/models/inventory_item.rb
class InventoryItem < ApplicationRecord
  belongs_to :shop
  belongs_to :product
  belongs_to :product_status
  belongs_to :employee
  has_many :transactions
  has_many :sales, through: :transactions
end

app/models/payment_detail.rb
class PaymentDetail < ApplicationRecord
  belongs_to :sale
end

app/models/player.rb
class Player < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :product_type
  belongs_to :product_subtype
  has_many :inventory_items
end

app/models/product_status.rb
class ProductStatus < ApplicationRecord
  has_many :inventory_items
  scope :as_option, ->{ where("id < 3") }#where({ product_status_id: [1, 2]})
  scope :managable_statuses, ->{ where(managable: 1) }
  scope :unmanagable_statuses, ->{ where(managable: 0) }
end

app/models/product_subtype.rb
class ProductSubtype < ApplicationRecord
  belongs_to :product_type
end

app/models/product_type.rb
class ProductType < ApplicationRecord
  has_many :products
  has_many :product_subtypes
end

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :shop
  belongs_to :employee
  has_many :sale_sessions
  has_many :payment_details
  has_many :transactions
  has_many :inventory_items, through: :transactions

  def create_sale_session
    SaleSession.find_or_create_by(sale: self, employee_id: self.employee_id)
  end

  def  destroy_sale_session
    #SaleSession.where(employee_id: current_user.employee_id).destroy_all
  end

  def test_dev_environ
    puts "################\n  Funciona!  \n################"
  end

  # def sell_inventory_items
  #   inventory_items = self.inventory_items
  #   inventory_items.each do |item|
  #     unless item.update(product_status_id: 4) then
  #       puts "\n\n#{item.errors}\n\n"
  #     end
  #   end
  # end

end

app/models/sale_session.rb
class SaleSession < ApplicationRecord
  belongs_to :employee
  belongs_to :sale
end

app/models/shop.rb
class Shop < ApplicationRecord
  has_many :employees
  has_many :inventory_items
  has_many :sales

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/test_api.rb
class TestApi < ApplicationRecord
    validates :fakeId, presence: true
    validates :title, presence: true
    validates :body, presence: true
    validates :userId, presence: true
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :sale
  belongs_to :inventory_item
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :employee


end

app/controllers/product_statuses_controller.rb
class ProductStatusesController < ApplicationController
  before_action :set_product_status, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /product_statuses
  # GET /product_statuses.json
  def index
    @product_statuses = ProductStatus.all
  end

  # GET /product_statuses/1
  # GET /product_statuses/1.json
  def show
  end

  # GET /product_statuses/new
  def new
    @product_status = ProductStatus.new
  end

  # GET /product_statuses/1/edit
  def edit
  end

  # POST /product_statuses
  # POST /product_statuses.json
  def create
    @product_status = ProductStatus.new(product_status_params)

    respond_to do |format|
      if @product_status.save
        format.html { redirect_to @product_status, notice: 'Product status was successfully created.' }
        format.json { render :show, status: :created, location: @product_status }
      else
        format.html { render :new }
        format.json { render json: @product_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product_statuses/1
  # PATCH/PUT /product_statuses/1.json
  def update
    respond_to do |format|
      if @product_status.update(product_status_params)
        format.html { redirect_to @product_status, notice: 'Product status was successfully updated.' }
        format.json { render :show, status: :ok, location: @product_status }
      else
        format.html { render :edit }
        format.json { render json: @product_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_statuses/1
  # DELETE /product_statuses/1.json
  def destroy
    @product_status.destroy
    respond_to do |format|
      format.html { redirect_to product_statuses_url, notice: 'Product status was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_status
      @product_status = ProductStatus.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_status_params
      params.require(:product_status).permit(:name, :managable)
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/product_statuses_helper.rb
module ProductStatusesHelper
end

app/helpers/revenue_helper.rb
module RevenueHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/product_statuses/_form.html.erb
<%= form_with(model: product_status, local: true) do |form| %>
  <% if product_status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product_status.errors.count, "error") %> prohibited this product_status from being saved:</h2>

      <ul>
        <% product_status.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :managable %>
    <%= form.number_field :managable %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/product_statuses/edit.html.erb
<h1>Editing Product Status</h1>

<%= render 'form', product_status: @product_status %>

<%= link_to 'Show', @product_status %> |
<%= link_to 'Back', product_statuses_path %>

app/views/product_statuses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Product Statuses</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Managable</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @product_statuses.each do |product_status| %>
      <tr>
        <td><%= product_status.name %></td>
        <td><%= product_status.managable %></td>
        <td><%= link_to 'Show', product_status %></td>
        <td><%= link_to 'Edit', edit_product_status_path(product_status) %></td>
        <td><%= link_to 'Destroy', product_status, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product Status', new_product_status_path %>

app/views/product_statuses/new.html.erb
<h1>New Product Status</h1>

<%= render 'form', product_status: @product_status %>

<%= link_to 'Back', product_statuses_path %>

app/views/product_statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product_status.name %>
</p>

<p>
  <strong>Managable:</strong>
  <%= @product_status.managable %>
</p>

<%= link_to 'Edit', edit_product_status_path(@product_status) %> |
<%= link_to 'Back', product_statuses_path %>